### ISSUE TITLE
figure out solution for tag coloring in activity view

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/owlet#132]
<img width="381" alt="screen shot 2016-11-11 at 4 31 23 pm" src="https://cloud.githubusercontent.com/assets/144226/20233420/87ba1050-a82c-11e6-886c-ee7d57cb66ca.png">

**AC**

- [ ] query contentful for all content models -> all content entries -> all Concepts in owlet-activies 
- [ ] create a data set for all tags 
- [ ] create a GET endpoint for the activities classier component 
- [ ] create PUT endpoint to update color and name
- [ ] normalize css vs CSS to lower-case
- [ ] come up with a way to programmatically generate a default tag color

**Comment by seandw** [comment]
For programmatically generating a default tag color, I suggest doing what most IRC clients do for coloring nicknames. Hash the text, and use that value to choose from a list of preset colors. [Here](https://github.com/weechat/weechat/blob/616d2ae295a301a1f96b627179f739d70c3f514a/src/gui/gui-nick.c#L38)'s an example in C, it would be far prettier (and simpler) in Clojure.

**Comment by eemshi** [comment]
can contentful help with this?
