### ISSUE TITLE
make activity tags (aka skills) searchable or filterable

### ISSUE THREAD

**Issue by eemshi** [codefordenver/owlet#149]
ACS
- [x] add skills list to owlet-api /branches GET request @dviramontes
- [x] design guide discovery @eemshi 
- [x] add re-com typeahead component @dviramontes
- [x] search bar in branches-view (breadcrumb bar becomes search bar) @ZadenRB 
- [x] style suggestion-render component @ZadenRB @dviramontes
- [x] take action on search term entered @dviramontes
- [ ] make search suggestions disappear when search bar loses focus and/or when nothing is typed in search bar @ZadenRB 
- [ ] empty search bar input on route navigation
- [x] display search-bar over content at all times @ZadenRB @dviramontes
- [x] fix results-suggestions highlight color

Filter all-activities by {criteria} below, render results in `:branch-activities-view` @dviramontes
- [x] by branch
- [x] by skill
- [ ] by activity name (title)
- [ ] by platform (techRequirements)
- [ ] by description text (this one is hard but doable)

**Comment by eemshi** [comment]
@dviramontes i think if we're going to have a search bar it should be all inclusive, meaning not just searching by *skills* but also *platform* (techRequirements), activity *title*, and *description*

**Comment by dviramontes** [comment]
yeah lets do it!

**Comment by dviramontes** [comment]
breaking this item down a bit more:
_filter all-activities by skill, render that in new view called search-results (view)_

search
- [ ] by branch
- [ ] by skill
- [ ] by activity name (title)
- [ ] by description text (this one is hard but doable)
- [ ] by platform (techRequirements)
