### ISSUE TITLE
owlet-ui build, test, & deploy flow

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/owlet#180]
Goal: low-cost (free) solution which is hosted and is low maintenance.  The primary goals are:
		1) Continuous Deployments to a Test environment, for any changes to the master branch
		2) Manually triggered deployments to production

Travis CI is currently in place, and is being used to performs continuous deployments to production.

<img width="787" alt="screen shot 2017-02-06 at 8 47 32 pm" src="https://cloud.githubusercontent.com/assets/144226/22677125/8651a47e-ecad-11e6-87f8-d89291f2c36d.png">

Steps to Complete:
- [x] create new s3 bucket for test deployments, so we have a second environment to use in addition to production
**Owlet test S3 bucket: owlet-dev.codefordenver.org**
- [x] Modify the travis.yml to push to the TBD test environment, instead of production
- [x] NOTE: Creation of test cases moved to issue #188 
- [x] Modify the travis.yml to dynamically determine which environment to deploy to, depending on branch
- [x] Modify the travis.yml to exclude all branches from the process (or at least the deployment), except for master (continous test deployment) and prod (production deployment) 
- [ ] Investigate: possible to use a script to set the vars as part of the build, and then travis.yml references those vars (this would keep the travis.yml simple), bonus points if all branches can be built/tested continuously but only prod branch is capable of deploying.  Ideally want a design where it would be easy/simple to add additional branches/environments/etc.
- [ ] Add a pre-commit hook (or similar) to enforce that the only allowable changes to the prod branch are from master -> prod pushes only (ideally, limit to a single force push/full overwrite command).
Git Hook Documentation: https://git-scm.com/docs/githooks
LOOK AT: pre-merge, pre-rebase, pre-commit (depending on "the command" that is allowed
UGH...not so easy on github, but see comments for an example pre-commit file

**Comment by danielritchie** [comment]
Example of pre-commit hook file:
`#!/bin/bash

#User Vars
NO_DIRECT_COMMITS="prod example-of-another-branch"

#Get some info
THIS_BRANCH=$(git rev-parse --abbrev-ref HEAD)

#Branches that only allow merges from master (to be used for deployment branches)
for i in ${NO_DIRECT_COMMITS}
do
    if [ "$i" == "$THIS_BRANCH" ] ; then	
        echo "Oh Noes! Direct commits to $THIS_BRANCH are not allowed."
        echo "It would be good to identify one approach that you are comfortable with, and update pre-commit.sh to only allow that command"
        echo "Using something like rebase with force push would be a good deterrent"
        exit 1
    fi
done
`
