### ISSUE TITLE
Setup s3 bucket + auto deploy for owlet-ui

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/owlet#21]
So that pushing to origin/master deploys to remote server.

**Comment by dviramontes** [comment]
Maybe @wdoug can help us with this one :)

**Comment by dviramontes** [comment]
We could even use a webhook for this.

**Comment by eemshi** [comment]
consider buying/renting own domain as part of this AC.

**Comment by eemshi** [comment]
connects to #20
