### ISSUE TITLE
Resolve compiler warning

### ISSUE THREAD

**Issue by eemshi** [codefordenver/owlet#222]

**Comment by tylerperkins** [comment]
@eemshi, the changes in my roles-and-authorization branch include many upgrades I made a couple weeks ago to most of the app's dependencies. They have eliminated most of the warnings. I also made changes to the build process that eliminates the cljs-devtools warning.

This amounted to a _lot_ of work, and if you'd like to merge roles-and-authorization, it's currently up to date with master  (as of 2017-04-28), so I could make a PR. I'm still working on it for the "roles" part.

**Comment by eemshi** [comment]
Oh cool, let's merge it in @tylerperkins
