### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by eemshi** [codefordenver/owlet#233]
- [x] Copy: https://docs.google.com/document/d/10cgKJ_ZxcR2OUkMV9O0oVKi7v0CW4tRRNN5AQNQrpcQ/edit?usp=sharing
- [x] Logos: CFD, Contentful
- [x] Refactor contentful.cljs to work without route-params
- [x] Add navigation link to the About page

**Comment by ZadenRB** [comment]
Link to github code?

**Comment by eemshi** [comment]
@ZadenRB  :+1:
