### ISSUE TITLE
feat: email notification for new activities

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/owlet#235]
As a user i would like the ability to subscribe to receive email notifications when new activities are added. 

---
ACS:

- [x] draft the email text
- [x] make initial component for signing up for content updates
- [x] add webhook to contetful for content creation
- [x] hook up endpoint to mmm/owlet-api resource for sending emails
- [x] write template for composing emails `hello #{name}, check out #{url}`
- [x] come up with UI for success email subscription
- [x] come up with UI for invalid (verify) email address input field
- [x] style component 
- [x] add email-notification component to filtered activities view(s)
- [x] create template for subscription email
- [x] add confirmation email for subscription
- [ ] add unsubscription to email
- [x] add UI for "already subscribed" emails
- [x] don't send email if revision > 1
- [x] only send email if new entry is an activity (not if it's a platform)

When a new activity is added to contentful we can send a webhook to owlet-backend to send an email.

![screen shot 2017-06-06 at 10 13 55 pm](https://user-images.githubusercontent.com/144226/26862095-d9466384-4b05-11e7-90fe-320594b5aa4f.png)
![screen shot 2017-06-06 at 10 14 09 pm](https://user-images.githubusercontent.com/144226/26862096-d9470e74-4b05-11e7-9812-617c8a491c90.png)

**Comment by ZadenRB** [comment]
Add direct link to new activity

**Comment by eemshi** [comment]
Confirmation email text, boosted from MailChimp!

>Owlet | New Activity Subscription

>Please Confirm Subscription by clicking this link.

>If you received this email by mistake, simply delete it. You won't be subscribed if you don't click the confirmation link above.

>For questions about this list, please contact: 
owlet@mmmanyfold.com
