### ISSUE TITLE
collapse email subscription component

### ISSUE THREAD

**Issue by eemshi** [codefordenver/owlet#240]
![subscribe-full.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/569dcda79e118a0e000cfbd0/125516c66e82c728ace21e0d46fb8198308191a08decf245b151fcd665043761260ea62864c7b96aea147e075e091dab45585912faaf8a29a6b63470db590fedc3714d36976345f3e5db55ea43a82a994d82bcbd8e45c8eb3e2def8e8f473e161755.png)

![subscribe-min.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/569dcda79e118a0e000cfbd0/125516c66e82c728ace21e0d46fb8198308191a08decf24ead53b2d86b56357c2301a03f32dfa17de9477d50090c49a8415e0942aafa8b2ba6be3c218f580bffcd7f1d2598694ef1e1c84afd13b03289498fb7b88344c3eb352de28b874f3d0c48.png)

- [ ] entire top bar should be clickable
- [ ] minimize by default for mobile

**Comment by dviramontes** [comment]
closed by https://github.com/codefordenver/owlet-ui/pull/163
