### ISSUE TITLE
feat: install and configure klipse, client side code eval

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/owlet#291]
https://github.com/viebel/klipse

**Comment by tylerperkins** [comment]
#### FYI

The page where I employed Klipse for the talk given by @eemshi and myself is [here](https://codefordenver.github.io/tutorials/intro-to-cljs/programming-functionally.html). Also see [my demo of Klipse](https://codefordenver.github.io/tutorials/intro-to-klipse/index.html). These applications of Klipse might come in handy for Owlet as well.

Note especially [klipse.html](https://github.com/codefordenver/tutorials/blob/master/_includes/klipse.html) and [pre-defs.html](https://github.com/codefordenver/tutorials/blob/master/_includes/pre-defs.html), which are used by [intro-to-cljs/programming-functionally.md](https://github.com/codefordenver/tutorials/blob/master/intro-to-cljs/programming-functionally.md) and [intro-to-klipse/index.md](https://github.com/codefordenver/tutorials/blob/master/intro-to-klipse/index.md).
