### ISSUE TITLE
KLIPSE || Validate slide advancement via Reveal.js

### ISSUE THREAD

**Issue by eemshi** [codefordenver/owlet#300]
AC's:
- [x] Request slides data from slides.com API
- [ ] Create code validations for slides that need it
- [ ] Disable next slide based on slide # and code validation
- [ ] Make it obvious when user can proceed to next slide (use sound and animation)

**Comment by ZadenRB** [comment]
Steps to allow disabling of horizontal navigation:
1. Get fonts
2. Copy <html> element from slides(live) to replace downloaded one
3. Copy <body> element from slides(live) to replace downloaded one
4. Copy <div class=“reveal”> element from slides(live) to replace downloaded one
6. Get configuration from loaded site for Reveal.initialize
7. Add Reveal.initalize({}); script
