### ISSUE TITLE
Fix Uberjar Warnings

### ISSUE THREAD

**Issue by ZadenRB** [codefordenver/owlet#307]
- [x] Move devtools to preloads
- [x] Move dirac to preloads
- [ ] Test dirac when in preloads
- [x] language_in option error find fix
- [ ] Regexp global reference fix

**Comment by ZadenRB** [comment]
![Screen Shot 2017-11-16 at 8.22.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57aa7a1bc524350e00bfead7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226455f56b7191a370f110294f5d575ecc3c4a4356bcbbd671f3e57862804e0eeb843b5e22953a15acbed419e902b8208b4785e7b98e4cd2f42f67b6d5db1063474f4dcbed5727a19e41c95df74be9455dad14316be0742431.png)

**Comment by dviramontes** [comment]
@ZadenRB can we PR this changes ?
We can create a new card for the dirac + global regexp  warnings
