### ISSUE TITLE
As a user (student | teacher) I would like to filter content by tags / model

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/owlet#40]
ACS:
- [x] Filter activities by category, such as web-design, robotics, movie-making, etc
- [x] render activity into activity-view in `activity.cljs`
- [x] solution for passing id that doesn't involve onclick

**Comment by eemshi** [comment]
Connects to #16, having a wireframe for the tags would be useful.

**Comment by dviramontes** [comment]
Technology and track are tags.

**Comment by dviramontes** [comment]
https://xd.adobe.com/view/1aaa8baf-b320-4ae8-7649-cc523e4ca95b/

**Comment by dviramontes** [comment]
_sudo code for matching track id to activity models in collection_
- from the first entry of :activities-by-track, take the content-type id `(-> data :sys :contentType :sys :id)`
- match against :model-id from :activity-models
- bind(assign) matched :name to <h1>
