### ISSUE TITLE
Make UI for owlet-status microservice

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/owlet#51]
Right now the service exists as backend only.
The API look like this
http://status.apps.aterial.org/api/ping/google.com

where the last part of the URL is the domain to ping
a more real example would be:
`http://status.apps.aterial.org/api/ping/`**owlet-cms.apps.aterial.org**
-  https://codefordenver.auth0.com/
- https://cdn.contentful.com/
- http://owlet-cms.apps.aterial.org/

**Comment by dviramontes** [comment]
http://jsbin.com/yoxitipisu/edit?html,js,console,output

**Comment by KeynesYouDigIt** [comment]
ffffiinally done (sorry)
