### ISSUE TITLE
Connect owlet-chat server to firebase presence endpoint

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/owlet#93]
From the user's perspective there are two main endpoints:

**AC**

- [ ] `/google-w43567` (username room) 

- [ ] `/teacher-role-doijr3o2i` (pending..)

**Comment by dviramontes** [comment]
@cjford the endpoint for firebase changed. Ping me when you get back in town.

**Comment by cjford** [comment]
Closed by [29cfccd](https://github.com/codefordenver/owlet-chat/commit/29cfccd41f780dd6f4a9e9e75e89773faffa9d8e). Users must be logged into Firebase to enter chat room.

See #111, #126, #127 for role-based rooms
